#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if test -d /home/linuxbrew/.linuxbrew/bin; then
  export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
fi

if ! command -v stow >/dev/null; then
  echo "ERROR: stow not found"
  exit 1
fi

STOW_PATH="$(command -v stow)"

restow() {
  "$STOW_PATH" --restow -d "${DIR}/stowed" "$@" 
}

# stow user binaries and configuration

non_linked_paths=(
  "${HOME}/.local/bin"
  "${HOME}/.config/"{fish,tilix}
  "${HOME}/.config/fish/"{conf.d,functions}
  "${HOME}/.aws"
  "${HOME}/.synced"
)

for path in "${non_linked_paths[@]}"; do
  mkdir -p "$path"
done

restow -t "$HOME" binaries
restow -t "${HOME}/.config/fish" fish
restow -t "$(rbenv root)" rbenv
restow -t "$(nodenv root)" nodenv
restow -t "$HOME" dotfiles
restow -t "$HOME" ubuntu-config
